kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: abcdb-operator-role
  namespace: abcdb
rules:
  - apiGroups: ["", "apps"]
    resources: ["services", "endpoints", "configmaps", "secrets", "pods", "deployments"]
    verbs: ["get", "watch", "list", "create", "delete", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
  - apiGroups: ["examples.micronaut.io"]
    resources: ["abcdbs"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: abcdb-operator-role-binding
  namespace: abcdb
subjects:
  - kind: ServiceAccount
    name: default
    namespace: abcdb
roleRef:
  kind: Role
  name: abcdb-operator-role
  apiGroup: rbac.authorization.k8s.io