apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: abcdbs.examples.micronaut.io
spec:
  group: examples.micronaut.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
      additionalPrinterColumns:
        - name: Message
          type: string
          description: The configured message
          jsonPath: .spec.message
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: abcdbs
    singular: abcdb
    kind: AbcDb
    shortNames:
      - db