apiVersion: v1
kind: Namespace
metadata:
  name: abcdb
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: abcdb-operator-role
  namespace: abcdb
rules:
  - apiGroups: ["", "apps"]
    resources: ["services", "endpoints", "configmaps", "secrets", "pods", "deployments"]
    verbs: ["get", "watch", "list", "create", "delete", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
  - apiGroups: ["examples.micronaut.io"]
    resources: ["abcdbs"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: abcdb-operator-role-binding
  namespace: abcdb
subjects:
  - kind: ServiceAccount
    name: default
    namespace: abcdb
roleRef:
  kind: Role
  name: abcdb-operator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: abcdbs.examples.micronaut.io
spec:
  group: examples.micronaut.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
      additionalPrinterColumns:
        - name: Message
          type: string
          description: The configured message
          jsonPath: .spec.message
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: abcdbs
    singular: abcdb
    kind: AbcDb
    shortNames:
      - db