/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.micronaut.examples.models;

import com.google.gson.annotations.SerializedName;
import io.kubernetes.client.openapi.models.V1ObjectMeta;
import io.kubernetes.client.openapi.models.V1ObjectMetaBuilder;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.examples.Application;
import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Objects;
import java.util.Optional;

import static io.micronaut.examples.AbcDbOperator.FINALIZER;

/**
 * V1AbcDb
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-30T14:51:15.545Z[Etc/UTC]")
@Introspected
public class V1AbcDb implements io.kubernetes.client.common.KubernetesObject {

  public static final String API_VERSION = "v1";
  public static final String KIND = "AbcDb";
  public static final String GROUP = "examples.micronaut.io";
  public static final String PLURAL = "abcdbs";
  public static final String NAMESPACE = "abcdb";

  public static final String SERIALIZED_NAME_API_VERSION = "apiVersion";
  public static final String RECONCILED_ANNOTATION = GROUP + "/reconciled";
  public static final String RECONCILIATION_TIMESTAMP_ANNOTATION = GROUP + "/reconciled-at";
  @SerializedName(SERIALIZED_NAME_API_VERSION)
  private String apiVersion;

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private String kind;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private V1ObjectMeta metadata = null;

  public static final String SERIALIZED_NAME_SPEC = "spec";
  @SerializedName(SERIALIZED_NAME_SPEC)
  private V1AbcDbSpec spec;

  public V1AbcDb(String name, String message) {
    this.metadata = new V1ObjectMetaBuilder()
            .withName(name)
            .addToLabels("app.kubernetes.io/name", Application.APP_NAME)
            .withNamespace("abcdb")
            .build();
    this.spec = new V1AbcDbSpec(message);
  }


  public V1AbcDb apiVersion(String apiVersion) {
    
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @return apiVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources")

  public String getApiVersion() {
    return apiVersion;
  }


  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }


  public V1AbcDb kind(String kind) {
    
    this.kind = kind;
    return this;
  }

   /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @return kind
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds")

  public String getKind() {
    return kind;
  }


  public void setKind(String kind) {
    this.kind = kind;
  }


  public V1AbcDb metadata(V1ObjectMeta metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ObjectMeta getMetadata() {
    if (this.metadata == null) {
      this.metadata = new V1ObjectMetaBuilder().build();
    }
    return metadata;
  }


  public void setMetadata(V1ObjectMeta metadata) {
    this.metadata = metadata;
  }


  public V1AbcDb spec(V1AbcDbSpec spec) {
    
    this.spec = spec;
    return this;
  }

   /**
   * Get spec
   * @return spec
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1AbcDbSpec getSpec() {
    return spec;
  }


  public void setSpec(V1AbcDbSpec spec) {
    this.spec = spec;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1AbcDb v1AbcDb = (V1AbcDb) o;
    return Objects.equals(this.apiVersion, v1AbcDb.apiVersion) &&
        Objects.equals(this.kind, v1AbcDb.kind) &&
        Objects.equals(this.metadata, v1AbcDb.metadata) &&
        Objects.equals(this.spec, v1AbcDb.spec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, kind, metadata, spec);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1AbcDb {\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  private void initAnnotations() {
    if (getMetadata().getAnnotations() == null) {
      getMetadata().setAnnotations(new HashMap<>());
    }
  }

  public boolean isReconciled() {
    initAnnotations();
    return getMetadata().getAnnotations().containsKey(RECONCILED_ANNOTATION);
  }

  public void setReconciled() {
    initAnnotations();
    getMetadata().getAnnotations().put(RECONCILED_ANNOTATION, Boolean.TRUE.toString());
    getMetadata().getAnnotations().put(RECONCILIATION_TIMESTAMP_ANNOTATION, OffsetDateTime.now().toString());
    getMetadata().addFinalizersItem(FINALIZER);
  }

  public String getName() {
    return Optional.ofNullable(getMetadata())
            .map(V1ObjectMeta::getName)
            .orElse("");
  }

  public boolean isBeingDeleted() {
    return getMetadata().getDeletionTimestamp() != null;
  }

  public void finalizeDeletion() {
    getMetadata().getFinalizers().clear();
  }

  public String getMessage() {
    return Optional.ofNullable(getSpec())
            .map(V1AbcDbSpec::getMessage)
            .orElse("");
  }
}

