/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.micronaut.examples.models;

import com.google.gson.annotations.SerializedName;
import io.kubernetes.client.openapi.models.V1ListMeta;
import io.kubernetes.client.openapi.models.V1ListMetaBuilder;
import io.micronaut.core.annotation.Introspected;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import static io.micronaut.examples.models.V1AbcDb.API_VERSION;

/**
 * AbcDbList is a list of AbcDb
 */
@ApiModel(description = "AbcDbList is a list of AbcDb")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-30T14:51:15.545Z[Etc/UTC]")
@Introspected
public class V1AbcDbList implements io.kubernetes.client.common.KubernetesListObject {

  private static final Logger LOG = LoggerFactory.getLogger(V1AbcDbList.class);

  public V1AbcDbList() {
    System.out.println("V1AbcDbList.V1AbcDbList");
    this.metadata = new V1ListMetaBuilder()
            .withResourceVersion(API_VERSION)
            .build();
  }

  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<V1AbcDb> items = new ArrayList<>();

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private V1ListMeta metadata = new V1ListMetaBuilder()
          .withResourceVersion("1")
          .build();

   /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @return apiVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources")

  public String getApiVersion() {
    System.out.println("V1AbcDbList.getApiVersion");
    return API_VERSION;
  }


  public V1AbcDbList items(List<V1AbcDb> items) {
    System.out.println("V1AbcDbList.items");
    this.items = items;
    return this;
  }

  public V1AbcDbList addItemsItem(V1AbcDb itemsItem) {
    System.out.println("V1AbcDbList.addItemsItem");
    this.items.add(itemsItem);
    return this;
  }

   /**
   * List of abcdbs. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
   * @return items
  **/
  @ApiModelProperty(required = true, value = "List of abcdbs. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md")

  public List<V1AbcDb> getItems() {
    System.out.println("V1AbcDbList.getItems");
    if (items == null) {
      items = new ArrayList<>();
    }
    return items;
  }


  public void setItems(List<V1AbcDb> items) {
    System.out.println("V1AbcDbList.setItems");
    this.items = items;
  }

   /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @return kind
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds")

  public String getKind() {
    System.out.println("V1AbcDbList.getKind");
    return V1AbcDb.KIND;
  }


  public V1AbcDbList metadata(V1ListMeta metadata) {
    System.out.println("V1AbcDbList.metadata");
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ListMeta getMetadata() {
    System.out.println("V1AbcDbList.getMetadata");
    if (metadata == null) {
      metadata = new V1ListMetaBuilder()
              .withResourceVersion("")
              .build();
    }
    return metadata;
  }


  public void setMetadata(V1ListMeta metadata) {
    System.out.println("V1AbcDbList.setMetadata");
    this.metadata = metadata;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1AbcDbList v1AbcDbList = (V1AbcDbList) o;
    return Objects.equals(this.items, v1AbcDbList.items) &&
        Objects.equals(this.metadata, v1AbcDbList.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items, metadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1AbcDbList {\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

